"""some more constraints on db

Revision ID: 0c3083016270
Revises: 80194de9cfdd
Create Date: 2021-08-27 19:12:08.705652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c3083016270'
down_revision = '80194de9cfdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_standardtaxrecords_taxname', table_name='standardtaxrecords')
    op.create_index(op.f('ix_standardtaxrecords_taxname'), 'standardtaxrecords', ['taxname'], unique=False)
    op.add_column('taxbill', sa.Column('taxable_value', sa.Integer(), nullable=False))
    op.alter_column('taxrecords', 'standardtax_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('taxrecords', 'standardtax_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('taxbill', 'taxable_value')
    op.drop_index(op.f('ix_standardtaxrecords_taxname'), table_name='standardtaxrecords')
    op.create_index('ix_standardtaxrecords_taxname', 'standardtaxrecords', ['taxname'], unique=False)
    # ### end Alembic commands ###
