"""empty message

Revision ID: 33f4c6a2b76c
Revises: 
Create Date: 2021-08-27 10:18:56.251823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33f4c6a2b76c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_roles_default'), 'roles', ['default'], unique=False)
    op.create_table('states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('statename', sa.String(length=25), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_states_statename'), 'states', ['statename'], unique=True)
    op.create_table('standardtaxrecords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('taxname', sa.String(length=10), nullable=True),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_standardtaxrecords_taxname'), 'standardtaxrecords', ['taxname'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('pancard', sa.String(length=10), nullable=True),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_pancard'), 'users', ['pancard'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('taxbill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payer_id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('billnumber', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['payer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_taxbill_billnumber'), 'taxbill', ['billnumber'], unique=True)
    op.create_table('taxrecords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('percent', sa.Float(), nullable=True),
    sa.Column('standardtax_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['standardtaxrecords.id'], ),
    sa.ForeignKeyConstraint(['standardtax_id'], ['standardtaxrecords.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('taxbillsstandardtaxrecordtaxes',
    sa.Column('taxbill_id', sa.Integer(), nullable=True),
    sa.Column('standardtaxrecord_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['standardtaxrecord_id'], ['standardtaxrecords.id'], ),
    sa.ForeignKeyConstraint(['taxbill_id'], ['taxbill.id'], )
    )
    op.create_table('taxbilltaxrecordpaidtaxes',
    sa.Column('taxbill_id', sa.Integer(), nullable=True),
    sa.Column('taxrecord_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['taxbill_id'], ['taxbill.id'], ),
    sa.ForeignKeyConstraint(['taxrecord_id'], ['taxrecords.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('taxbilltaxrecordpaidtaxes')
    op.drop_table('taxbillsstandardtaxrecordtaxes')
    op.drop_table('taxrecords')
    op.drop_index(op.f('ix_taxbill_billnumber'), table_name='taxbill')
    op.drop_table('taxbill')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_pancard'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_standardtaxrecords_taxname'), table_name='standardtaxrecords')
    op.drop_table('standardtaxrecords')
    op.drop_index(op.f('ix_states_statename'), table_name='states')
    op.drop_table('states')
    op.drop_index(op.f('ix_roles_default'), table_name='roles')
    op.drop_table('roles')
    # ### end Alembic commands ###
