"""many many relation btw Taxbill & standardtaxrecord for taxes 

Revision ID: 4b9cadf64581
Revises: aa3773e4b0b8
Create Date: 2021-08-26 15:51:21.314422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b9cadf64581'
down_revision = 'aa3773e4b0b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taxbillsstandardtaxrecordtaxes',
    sa.Column('taxbill_id', sa.Integer(), nullable=True),
    sa.Column('standardtaxrecord_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['standardtaxrecord_id'], ['standardtaxrecords.id'], ),
    sa.ForeignKeyConstraint(['taxbill_id'], ['taxbill.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('taxbillsstandardtaxrecordtaxes')
    # ### end Alembic commands ###
