"""association table both keys primary to make unique

Revision ID: 55e99a4eaddb
Revises: 0c3083016270
Create Date: 2021-08-28 01:57:15.707341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55e99a4eaddb'
down_revision = '0c3083016270'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_standardtaxrecords_taxname', table_name='standardtaxrecords')
    op.alter_column('taxbillsstandardtaxrecordtaxes', 'taxbill_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('taxbillsstandardtaxrecordtaxes', 'standardtaxrecord_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('taxbilltaxrecordpaidtaxes', 'taxbill_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('taxbilltaxrecordpaidtaxes', 'taxrecord_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('taxbilltaxrecordpaidtaxes', 'taxrecord_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('taxbilltaxrecordpaidtaxes', 'taxbill_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('taxbillsstandardtaxrecordtaxes', 'standardtaxrecord_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('taxbillsstandardtaxrecordtaxes', 'taxbill_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index('ix_standardtaxrecords_taxname', 'standardtaxrecords', ['taxname'], unique=False)
    # ### end Alembic commands ###
