"""TaxRecord table

Revision ID: 79358123281b
Revises: d20d4d319daa
Create Date: 2021-08-26 12:28:29.532071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79358123281b'
down_revision = 'd20d4d319daa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taxrecords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('percent', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('standardtaxrecords', sa.Column('activerecord_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'standardtaxrecords', 'taxrecords', ['activerecord_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'standardtaxrecords', type_='foreignkey')
    op.drop_column('standardtaxrecords', 'activerecord_id')
    op.drop_table('taxrecords')
    # ### end Alembic commands ###
