"""Nullable conditions implied

Revision ID: 80194de9cfdd
Revises: 33f4c6a2b76c
Create Date: 2021-08-27 18:49:16.737486

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '80194de9cfdd'
down_revision = '33f4c6a2b76c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roles', 'name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('standardtaxrecords', 'taxname',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.drop_index('ix_standardtaxrecords_taxname', table_name='standardtaxrecords')
    op.create_index(op.f('ix_standardtaxrecords_taxname'), 'standardtaxrecords', ['taxname'], unique=True)
    op.create_unique_constraint('unique_taxname_state_id', 'standardtaxrecords', ['taxname', 'state_id'])
    op.alter_column('states', 'statename',
               existing_type=sa.VARCHAR(length=25),
               nullable=False)
    op.alter_column('taxbill', 'due_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('taxrecords', 'percent',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('users', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('taxrecords', 'percent',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('taxbill', 'due_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('states', 'statename',
               existing_type=sa.VARCHAR(length=25),
               nullable=True)
    op.drop_constraint('unique_taxname_state_id', 'standardtaxrecords', type_='unique')
    op.drop_index(op.f('ix_standardtaxrecords_taxname'), table_name='standardtaxrecords')
    op.create_index('ix_standardtaxrecords_taxname', 'standardtaxrecords', ['taxname'], unique=False)
    op.alter_column('standardtaxrecords', 'taxname',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('roles', 'name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    # ### end Alembic commands ###
