"""unique constraint

Revision ID: 8a2b9f994160
Revises: ba3d20b32ee7
Create Date: 2021-08-28 09:35:11.179248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a2b9f994160'
down_revision = 'ba3d20b32ee7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uniquekeypairs1', 'taxbillsstandardtaxrecordtaxes', ['taxbill_id', 'standardtaxrecord_id'])
    op.create_unique_constraint('uniquekeypairs2', 'taxbilltaxrecordpaidtaxes', ['taxbill_id', 'taxrecord_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uniquekeypairs2', 'taxbilltaxrecordpaidtaxes', type_='unique')
    op.drop_constraint('uniquekeypairs1', 'taxbillsstandardtaxrecordtaxes', type_='unique')
    # ### end Alembic commands ###
