"""States table [id name residents] Users [state pancard]

Revision ID: 908880eb7029
Revises: 436ee3b56f12
Create Date: 2021-08-25 19:09:50.235311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '908880eb7029'
down_revision = '436ee3b56f12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('statename', sa.String(length=25), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_states_statename'), 'states', ['statename'], unique=True)
    op.add_column('users', sa.Column('pancard', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('state_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_pancard'), 'users', ['pancard'], unique=True)
    op.create_foreign_key(None, 'users', 'states', ['state_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_pancard'), table_name='users')
    op.drop_column('users', 'state_id')
    op.drop_column('users', 'pancard')
    op.drop_index(op.f('ix_states_statename'), table_name='states')
    op.drop_table('states')
    # ### end Alembic commands ###
