"""one to many stdtaxrecords to taxrec

Revision ID: aa3773e4b0b8
Revises: 79358123281b
Create Date: 2021-08-26 12:43:05.801973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa3773e4b0b8'
down_revision = '79358123281b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taxrecords', sa.Column('standardtax_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'taxrecords', 'standardtaxrecords', ['standardtax_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'taxrecords', type_='foreignkey')
    op.drop_column('taxrecords', 'standardtax_id')
    # ### end Alembic commands ###
