"""removed null constraints

Revision ID: ba3d20b32ee7
Revises: d35975d575b3
Create Date: 2021-08-28 09:11:34.345937

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ba3d20b32ee7'
down_revision = 'd35975d575b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roles', 'name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('standardtaxrecords', 'taxname',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('states', 'statename',
               existing_type=sa.VARCHAR(length=25),
               nullable=True)
    op.alter_column('taxbill', 'payer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('taxbill', 'creator_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('taxbill', 'billnumber',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('taxbill', 'taxable_value',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('taxbill', 'due_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('taxbill', 'status',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('taxrecords', 'percent',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('users', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('taxrecords', 'percent',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('taxbill', 'status',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('taxbill', 'due_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('taxbill', 'taxable_value',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('taxbill', 'billnumber',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('taxbill', 'creator_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('taxbill', 'payer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('states', 'statename',
               existing_type=sa.VARCHAR(length=25),
               nullable=False)
    op.alter_column('standardtaxrecords', 'taxname',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('roles', 'name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    # ### end Alembic commands ###
