"""all relations except (stdtax and taxrec) 

Revision ID: d2f7e25ebec6
Revises: 
Create Date: 2021-08-26 18:12:22.717589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2f7e25ebec6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_roles_default'), 'roles', ['default'], unique=False)
    op.create_table('states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('statename', sa.String(length=25), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_states_statename'), 'states', ['statename'], unique=True)
    op.create_table('taxrecords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('percent', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('standardtaxrecords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('taxname', sa.String(length=10), nullable=True),
    sa.Column('activerecord_id', sa.Integer(), nullable=True),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['activerecord_id'], ['taxrecords.id'], ),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_standardtaxrecords_taxname'), 'standardtaxrecords', ['taxname'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('pancard', sa.String(length=10), nullable=True),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_pancard'), 'users', ['pancard'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('taxbill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payer_id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('billnumber', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['payer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_taxbill_billnumber'), 'taxbill', ['billnumber'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_taxbill_billnumber'), table_name='taxbill')
    op.drop_table('taxbill')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_pancard'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_standardtaxrecords_taxname'), table_name='standardtaxrecords')
    op.drop_table('standardtaxrecords')
    op.drop_table('taxrecords')
    op.drop_index(op.f('ix_states_statename'), table_name='states')
    op.drop_table('states')
    op.drop_index(op.f('ix_roles_default'), table_name='roles')
    op.drop_table('roles')
    # ### end Alembic commands ###


# INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
# INFO  [alembic.runtime.migration] Will assume transactional DDL.
# INFO  [alembic.autogenerate.compare] Detected added table 'roles'
# INFO  [alembic.autogenerate.compare] Detected added index 'ix_roles_default' on '['default']'
# INFO  [alembic.autogenerate.compare] Detected added table 'states'
# INFO  [alembic.autogenerate.compare] Detected added index 'ix_states_statename' on '['statename']'
# INFO  [alembic.autogenerate.compare] Detected added table 'taxrecords'
# INFO  [alembic.autogenerate.compare] Detected added table 'standardtaxrecords'
# INFO  [alembic.autogenerate.compare] Detected added index 'ix_standardtaxrecords_taxname' on '['taxname']'
# INFO  [alembic.autogenerate.compare] Detected added table 'users'
# INFO  [alembic.autogenerate.compare] Detected added index 'ix_users_email' on '['email']'
# INFO  [alembic.autogenerate.compare] Detected added index 'ix_users_pancard' on '['pancard']'
# INFO  [alembic.autogenerate.compare] Detected added index 'ix_users_username' on '['username']'
# INFO  [alembic.autogenerate.compare] Detected added table 'taxbill'
# INFO  [alembic.autogenerate.compare] Detected added index 'ix_taxbill_billnumber' on '['billnumber']'
# Generating C:\Users\akshi\Desktop\flask assignment\migrations\versions\d2f7e25ebec6_all_relations_except_stdtax_and_taxrec.py ...  done