"""empty message

Revision ID: d35975d575b3
Revises: 55e99a4eaddb
Create Date: 2021-08-28 02:11:28.235140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd35975d575b3'
down_revision = '55e99a4eaddb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('taxrecords', 'standardtax_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('taxrecords', 'standardtax_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
