"""many many relation btw Taxbill & Taxrecord for bills paid 

Revision ID: e4e3cb1b934f
Revises: 4b9cadf64581
Create Date: 2021-08-26 15:56:48.743657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4e3cb1b934f'
down_revision = '4b9cadf64581'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taxbilltaxrecordpaidtaxes',
    sa.Column('taxbill_id', sa.Integer(), nullable=True),
    sa.Column('taxrecord_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['taxbill_id'], ['taxbill.id'], ),
    sa.ForeignKeyConstraint(['taxrecord_id'], ['taxrecords.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('taxbilltaxrecordpaidtaxes')
    # ### end Alembic commands ###
