"""Nullable changes in Taxbill

Revision ID: f57d74f2b215
Revises: f54af22b4110
Create Date: 2021-08-25 23:06:03.237878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f57d74f2b215'
down_revision = 'f54af22b4110'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('taxbill', 'payer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('taxbill', 'creator_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('taxbill', 'billnumber',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('taxbill', 'status',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('taxbill', 'status',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('taxbill', 'billnumber',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('taxbill', 'creator_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('taxbill', 'payer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
